version: '1'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    depends_on:
      - docker

  docker:
    image: docker:dind
    privileged: true
volumes:
  jenkins_home:

